-- 서브쿼리를 이용해 두 테이블을 비교하여 없는 값 찾기
SELECT A.* 
  FROM TMPDISDGT A
 WHERE A.DIAGESERL NOT IN(SELECT B.ICDTSEQ FROM BASSANGCD B)


-- LEFT JOIN을 이용해 두 테이블을 비교하여 없는 값 찾기
SELECT A.* 
  FROM TMPDISDGT A
  LEFT JOIN BASSANGCD B ON A.DIAGESERL = B.ICDTSEQ
 WHERE A.DIAGESERL IS NULL 

